language: ruby
rvm:
  - 2.1.0
install: 
  - bundle install
cache: bundler
before_script: 
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: rake travis:travis
services:
  - elasticsearch
notifications:
  email:
    - nkcr.je@gmail.com
    - kocher.ke@gmail.com