language: ruby
rvm:
  - 2.1.5
install: 
  - bundle install
cache: bundler
before_script: 
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database resj_test;' -U postgres
  - cp config/deploy/config/database.yml config/database.yml
  - cp config/deploy/config/elasticsearch.yml config/elasticsearch.yml
script: rake travis:travis
services:
  - elasticsearch
notifications:
  email:
    - nkcr.je@gmail.com
    - kocher.ke@gmail.com