development:
  adapter: postgresql
  encoding: unicode
  database: resj_development
  pool: 5
  host: localhost
  username: khcr
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: resj_test
  pool: 5
  host: localhost
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: resj_production
  pool: 5
  host: localhost
  username: resj
  password: 

staging:
  adapter: postgresql
  encoding: unicode
  database: resj_staging
  pool: 5
  host: localhost
  username: resj
  password: 

cucumber:
  <<: *test