default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] or "localhost" %>
  username: <%= ENV['POSTGRES_USER'] or "khcr" %>
  pool: 5

development:
  <<: *default
  database: resj_development

test:
  <<: *default
  database: resj_test

production:
  <<: *default
  database: resj_production
  username: resj
  password: