production:
  solr:
    hostname: localhost
    port: 8080
    path: /solr
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8080
    log_level: INFO
    path: /solr

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
# catalina start